### ISSUE TITLE
From server side perspective

### ISSUE THREAD

**Issue by dbrezoev** [RajanRastogi/angular-quartz-cron#3]
If my server is nodejs. How do you use the quartz format? What nodejs library do you use?

**Comment by RajanRastogi** [comment]
Well, it has been a while since I used cron on node.js, but there are multiple libraries available. These are some I googled and seemed okay to act as schedulers:

https://github.com/node-schedule/node-schedule

https://github.com/kelektiv/node-cron

As for the cron format, that is something specific to the library. Both the above seem to use the Quartz format of cron.

Let me know if you need anything else or if I have misunderstood your question. Otherwise, we can close the issue.

**Comment by dbrezoev** [comment]
Thank you for responding. I tried these two already. They don`t recognize angular quartz cron format. Additional parsing is needed I think. Anyway you can close this issue.

**Comment by RajanRastogi** [comment]
Hi,

Sorry, I am wrong, both with work with regular linux cron expressions. You might want to use the following project:

https://github.com/angular-cron-jobs/angular-cron-jobs

That project has switchable expressions, so you can configure which type of cron expression to use. This project has been merged into it to provide support for quartz-style cron.
